apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
    - port: 1
      name: hello-world
  clusterIP: None
  selector:
    app: hello-world
  #type: LoadBalancer