openapi: 3.0.0
info:
  version: 1.0.0
  title: OHOS Neptune EC2 api
servers:
  - url: ec2-13-40-156-226.eu-west-2.compute.amazonaws.com:5000
paths:
  /:
    get:
      description: Test 
      responses:
        '200':
          description: Conformation the API is alive
          content:
            application/json:
              schema:
                type: object 
                properties:           
                  message:
                    type: string
  /sparql:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                sparqlstring:
                  type: string
                limit:
                  type: string
                required:
                  - sparqlstring
                  - limit
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sparqlResponse"
        "400":
          description: Bad Request
          content:
            text/html:
              schema:
                type: string
                example: Something went wrong!
        "500":
          description: Internal Server Error
          content:
            text/html:
              schema:
                type: string
                example: Something went wrong!
  
  /movingImages:
    get:
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: Keyword to search for
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: true
          description: Page of results to look for
      description:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/movingImagesResponse"
        '204':
          description: No Content. Search didn't error, but returned no responses.
        '400':
          description: Bad Request. User error in the search; search term missing or similar. 
        '416':
          description: Range Not Satisfiable. User has requested a page number of results higher than exists for this search. 
        '500':
          description: Internal server error. Something went wrong in the server. 

components:
  schemas:
    sparqlResponse:
      properties:
        head:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/sparqlHeadVars'
        results:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/sparqlResultsBindings'
    
    sparqlHeadVars:
      type: string array

    sparqlResultsBindings:
      bindings:
        type: object array
        additionalProperties:
          $ref: '#/components/schemas/sparqlResults'

    sparqlResults:
      o:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/sparqlResultsSpecific'
      p:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/sparqlResultsSpecific'
      s:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/sparqlResultsSpecific'

    sparqlResultsSpecific:
      type:
        type: string
      value:
        type: string

    movingImagesResponse:
      properties:
        id:
          type: array
          additionalProperties:
            $ref: "#/components/schemas/movingImagesId"
        total:
          type: integer
        first:
          type: string
        prev:
          type: string
        next:
          type: string
        last:
          type: string
        items:
          type: array
          additionalProperties:
            $ref: "#/components/schemas/movingImagesItem"
      
    movingImagesItem:
      properties:
        type:
          type: string
        value:
          type: string

    movingImagesId:
      properties:
        page:
          type: string
        keyword:
          type: string