version: "3.9"
networks:
  default:
    name: kong-net
services:
  kong:
    image: kong:alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stdout"
      KONG_ADMIN_ERROR_LOG: "/dev/stdout"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
      - "5000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  
  goapi:
    image: public.ecr.aws/j8z6n5u1/data-go-api:latest
    hostname: goapi
    container_name: goapi
    env_file:
      - ${CURRENT_ENV}.env
    ports:
      - "9000:9000"

  frontend:
    image: public.ecr.aws/j8z6n5u1/data-go-ui:latest
    hostname: frontend
    container_name: frontend
    ports:
      - 3000

  dashui:
    image: public.ecr.aws/j8z6n5u1/ohos-dash-ui
    hostname: dashui
    container_name: dashui
    ports:
      - 8050:8050