apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  KONG_DATABASE_KEY: "off"
  KONG_PROXY_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_PROXY_ERROR_LOG_KEY: "/dev/stdout"
  KONG_ADMIN_ERROR_LOG_KEY: "/dev/stdout"
  KONG_PROXY_LISTEN_KEY: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  KONG_ADMIN_LISTEN_KEY: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_DECLARATIVE_CONFIG_KEY: "/etc/config/kong.yml"
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:

      - name: goapi
        url: http://goapi
        port: 9000
        routes:
          - name: goapi
            paths:
              - /
            preserve_host: true
            strip_path: true
            methods:
              - GET
              - POST

    plugins:
    - name: cors
      service: goapi
      config: 
        origins:
        - '*'
        methods:
        - GET
        - HEAD
        - OPTIONS
        credentials: true
        max_age: 3600