apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
      #app.kubernetes.io/name: go-api
  template:
    metadata:
      labels:
        app: http-echo
        #app.kubernetes.io/name: go-api
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          #imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
              name: http-echo
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
