apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpecho
      #app.kubernetes.io/name: go-api
  template:
    metadata:
      labels:
        app: httpecho
        #app.kubernetes.io/name: go-api
    spec:
      containers:
        - name: httpecho
          image: hashicorp/http-echo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
              name: httpecho
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
