apiVersion: v1
kind: Service
metadata:
  name: httpecho
  labels:
    app: httpecho
spec:
  ports:
    - port: 5678
      name: httpecho
  clusterIP: None
  selector:
    app: httpecho
  #type: LoadBalancer
