apiVersion: v1
kind: Service
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  ports:
    - port: 5678
      name: http-echo
  clusterIP: None
  selector:
    app: http-echo
  #type: LoadBalancer
