apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: goapi
          ports:
            - containerPort: 9000
              name: goapi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
