version: "3.9"
networks:
  default:
    name: kong-net
services:
  kong:
    image: kong:alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stdout"
      KONG_ADMIN_ERROR_LOG: "/dev/stdout"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  
  echotest:
    image: public.ecr.aws/j8z6n5u1/echotest:latest
    hostname: echotest
    container_name: echotest
    ports:
      - "5050:5050"

  miiify:
    image: jptmoore/miiify
    hostname: miiify
    container_name: miiify
    ports:
      - "8080:8080" 