_format_version: "2.1"
_transform: true

services: 

  - name: echotest
    url: http://echotest:5050/
    routes:
      - name: echotest
        paths:
          - /echo
        strip_path: true
        methods:
          - GET