basePath: /api
definitions:
  main.BindingsTitleTopicUrlDescription:
    properties:
      description:
        $ref: '#/definitions/main.TitleTopicStructValues'
      identifier:
        $ref: '#/definitions/main.IdentifierReturnValues'
      title:
        $ref: '#/definitions/main.TitleTopicStructValues'
      topics:
        $ref: '#/definitions/main.TitleTopicStructValues'
      url:
        $ref: '#/definitions/main.URLReturnValues'
    type: object
  main.DiscoveryCodeCount:
    properties:
      code:
        type: string
      count:
        type: integer
    type: object
  main.DiscoveryRecordDetails:
    properties:
      adminHistory:
        type: string
      altName:
        type: string
      arrangement:
        type: string
      catalogueLevel:
        type: integer
      closureCode:
        type: string
      closureStatus:
        type: string
      closureType:
        type: string
      content:
        type: string
      context:
        type: string
      corpBodies:
        items:
          type: string
        type: array
      coveringDates:
        type: string
      department:
        type: string
      description:
        type: string
      documentType:
        type: string
      endDate:
        type: string
      formerReferenceDep:
        type: string
      formerReferencePro:
        type: string
      heldBy:
        items:
          type: string
        type: array
      id:
        type: string
      mapDesignation:
        type: string
      mapScale:
        type: string
      note:
        type: string
      numEndDate:
        type: integer
      numStartDate:
        type: integer
      openingDate:
        type: string
      physicalCondition:
        type: string
      places:
        items:
          type: string
        type: array
      reference:
        type: string
      score:
        type: integer
      source:
        type: string
      startDate:
        type: string
      taxonomies:
        items:
          type: string
        type: array
      title:
        type: string
      urlParameters:
        type: string
    type: object
  main.EntityReturnStruct:
    properties:
      items:
        items:
          $ref: '#/definitions/main.BindingsTitleTopicUrlDescription'
        type: array
    type: object
  main.IdentifierReturnValues:
    properties:
      type:
        type: string
      value:
        type: string
    type: object
  main.KeywordStruct:
    properties:
      keyword:
        type: string
      page:
        type: string
    type: object
  main.TitleTopicStructValues:
    properties:
      type:
        type: string
      value:
        type: string
    type: object
  main.URLReturnValues:
    properties:
      datatype:
        type: string
      type:
        type: string
      value:
        type: string
    type: object
  main.discoveryAllStruct:
    properties:
      cagalogueLevels:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      closureStatuses:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      count:
        type: integer
      departments:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      heldByReps:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      nextBatchMark:
        type: string
      records:
        items:
          $ref: '#/definitions/main.DiscoveryRecordDetails'
        type: array
      referenceFirstLetters:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      repositories:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      sources:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      taxonomySubject:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      timePeriods:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
      titleFirstLetters:
        items:
          $ref: '#/definitions/main.DiscoveryCodeCount'
        type: array
    type: object
  main.keywordReturnStruct:
    properties:
      first:
        type: string
      id:
        $ref: '#/definitions/main.KeywordStruct'
      items:
        items:
          $ref: '#/definitions/main.BindingsTitleTopicUrlDescription'
        type: array
      last:
        type: string
      next:
        type: string
      prev:
        type: string
      total:
        type: integer
    type: object
host: ec2-13-40-156-226.eu-west-2.compute.amazonaws.com:5000
info:
  contact:
    name: The National Archives
  description: OHOS api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OHOS api
  version: 1.0.1
paths:
  /:
    get:
      description: Test whether the api is running
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Test whether the API is running
      tags:
      - root
  /discovery:
    get:
      description: Requests to TNA Discovery API
      parameters:
      - description: string query
        in: query
        name: q
        required: true
        type: string
      - description: string sourceArchives
        in: query
        name: source
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.discoveryAllStruct'
      summary: Requests to TNA Discovery API
      tags:
      - Discovery
  /moving-images:
    get:
      description: Moving images queries
      parameters:
      - description: string query
        in: query
        name: q
        required: true
        type: string
      - description: int page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Moving images queries
      tags:
      - MovingImages
   
  /archives/:
    get:
      description: archives queries
      parameters:
      - description: string archive
        in: query
        name: archive
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive agent
        in: query
        name: archive-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive place
        in: query
        name: archive-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive event
        in: query
        name: archive-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive object
        in: query
        name: archive-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection
        in: query
        name: collection
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection agent
        in: query
        name: collection-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection place
        in: query
        name: collection-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection event
        in: query
        name: collection-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection object
        in: query
        name: collection-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document
        in: query
        name: document
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document agent
        in: query
        name: document-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document place
        in: query
        name: document-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document event
        in: query
        name: document-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document object
        in: query
        name: document-object
        required: false
        schema:
          type: array
          items:
            types: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: archive queries
      tags:
      - archive

  /archives/{id}:
    get:
      description: archives queries
      parameters:
      - description: string id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: archive queries
      tags:
      - archive

  /collections/{id}:
    get:
      description: collections queries
      parameters:
      - description: string id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: collection queries
      tags:
      - collection

  /collections/:
    get:
      description: collections queries
      parameters:
      - description: string archive
        in: query
        name: archive
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive agent
        in: query
        name: archive-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive place
        in: query
        name: archive-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive event
        in: query
        name: archive-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive object
        in: query
        name: archive-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection
        in: query
        name: collection
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection agent
        in: query
        name: collection-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection place
        in: query
        name: collection-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection event
        in: query
        name: collection-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection object
        in: query
        name: collection-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document
        in: query
        name: document
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document agent
        in: query
        name: document-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document place
        in: query
        name: document-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document event
        in: query
        name: document-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document object
        in: query
        name: document-object
        required: false
        schema:
          type: array
          items:
            types: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: collection queries
      tags:
      - collection

  /documents/:
    get:
      description: documents queries
      parameters:
      - description: string archive
        in: query
        name: archive
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive agent
        in: query
        name: archive-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive place
        in: query
        name: archive-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive event
        in: query
        name: archive-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string archive object
        in: query
        name: archive-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection
        in: query
        name: collection
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection agent
        in: query
        name: collection-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection place
        in: query
        name: collection-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection event
        in: query
        name: collection-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string collection object
        in: query
        name: collection-object
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document
        in: query
        name: document
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document agent
        in: query
        name: document-agent
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document place
        in: query
        name: document-place
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document event
        in: query
        name: document-event
        required: false
        schema:
          type: array
          items:
            types: string
      - description: string document object
        in: query
        name: document-object
        required: false
        schema:
          type: array
          items:
            types: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: document queries
      tags:
      - document

  /documents/{id}:
    get:
      description: documents queries
      parameters:
      - description: string id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: document queries
      tags:
      - document

  /moving-images-ent/entity/{id}:
    get:
      description: Moving images get specific entity query
      parameters:
      - description: string id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.EntityReturnStruct'
        "500":
          description: Internal Server Error
      summary: Moving images get specific entity query
      tags:
      - MovingImages Entity
  /sparql:
    post:
      consumes:
      - application/json
      description: Send sparql direct to neptune
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Send sparql direct to neptune
      tags:
      - Sparql
swagger: "2.0"