definitions:
  main.BindingsResultsTitleTopic:
    properties:
      title:
        $ref: '#/definitions/main.TitleTopicStructValues'
      topics:
        $ref: '#/definitions/main.TitleTopicStructValues'
    type: object
  main.KeywordStruct:
    properties:
      keyword:
        type: string
      page:
        type: string
    type: object
  main.TitleTopicStructValues:
    properties:
      type:
        type: string
      value:
        type: string
    type: object
  main.keywordReturnStruct:
    properties:
      first:
        type: string
      id:
        $ref: '#/definitions/main.KeywordStruct'
      items:
        items:
          $ref: '#/definitions/main.BindingsResultsTitleTopic'
        type: array
      last:
        type: string
      next:
        type: string
      prev:
        type: string
      total:
        type: integer
    type: object
info:
  contact:
    name: The National Archives
  description: OHOS api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OHOS api
  version: "1.0"
paths:
  /:
    get:
      description: Test whether the api is running
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Test whether the API is running
      tags:
      - root
  /discovery:
    get:
      description: Requests to TNA Discovery API
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Requests to TNA Discovery API
      tags:
      - Discovery
  /movingImages:
    get:
      description: Moving images queries
      parameters:
      - description: string query
        in: query
        name: q
        required: true
        type: string
      - description: int page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.keywordReturnStruct'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Moving images queries
      tags:
      - MovingImages
  /sparql:
    post:
      consumes:
      - application/json
      description: Send sparql direct to neptune
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Send sparql direct to neptune
      tags:
      - Sparql
swagger: "2.0"
